baseURL = ""
languageCode = "en-us"
title = "Robotics Engineer | Liz Miller"
theme = "hugo-lime"
googleAnalytics = "UA-98320078-1"

# SEO
enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
#[permalinks]
#post = "/blog/:title/"

[params]
# head description
# This is what appears on the preview when posting this site on Facebook for example
description = "Robotics & Automation by Liz Miller"

# head photo
# This is what appears on the preview when posting this site on Facebook for example
description_photo = "robotics.png"

[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.48"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
